- name: install nfs-common on ubuntu
  apt:
    name: nfs-common
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: install nfs-utils on ubuntu
  yum:
    name: nfs-utils
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: copy iscsi to kubernetes master
  copy:
    src: "{{ LONG_HORN_FILE }}/longhorn-nfs-installation.yaml"
    dest: /root/longhorn-nfs-installation.yaml
  when: inventory_hostname in groups['master_kuber']

- name: install open-iscsi on centos
  shell: |
    kubectl apply -f /root/longhorn-nfs-installation.yaml
  when: inventory_hostname in groups['master_kuber']
